### PR TITLE
Use correct MultiConfig class

### PR DESCRIPTION
**Pull request by ryderwishart**
All morning I was working on creating this functionality, and then I found your fork! Thank you, and great job so far!

### Background
The command line args (e.g., `--gpt3only`) were not making it to the `MultiConfig()`, only the `Config()`. This would result in the following error:
```python
Debug Mode:  ENABLED
GPT3.5 Only Mode:  ENABLED
FAST MODEL: gpt-3.5-turbo 
SMART MODEL BEFORE: gpt-4 # note: value from .env
SMART MODEL AFTER: gpt-3.5-turbo  # note: parsed command line args
Welcome to MultiGPT!  I am the orchestrator of your AI assistants.
Define the task you want to accomplish and I will gather a group of expertGPTs to help you.  Be specific. Prefer 'Achieve world domination by creating a raccoon army!' to 'Achieve world domination!'
Task: Achieve world peace by creating a raccoon band!
Creating chat completion with model gpt-4, temperature 0.1, max_tokens 1000 # note: you can see it's trying to use the .env smart model
Traceback (most recent call last):
...
openai.error.InvalidRequestError: The model: `gpt-4` does not exist
```

### Changes
I switched out the config class from `autogpt.config.Config` to `multigpt.multi_config.MultiConfig`.

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [x] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by ryderwishart** [comment]
I've noticed, in addition, that the `y -n` input is not correctly tracking `-n`—it only approves one command. I'm looking into this.

**Comment by KevinHenkes** [comment]
I have find another bug for who want use only gpt 3, in Multi-GPT/multigpt/lmql_utils/_queries.py, the function generate_experts is hard coded "from openai/gpt-4".

**Comment by ruflair** [comment]
Just wanted to thank everyone for the input. We have been preoccupied the last couple of days and didn't have much time to work on this project. We will now focus on building Multi-GPT and fixing bugs.

**Comment by ruflair** [comment]
> I have find another bug for who want use only gpt 3, in Multi-GPT/multigpt/lmql_utils/_queries.py, the function generate_experts is hard coded "from openai/gpt-4".

This is now fixed. There is not a lot of documentation for LMQL (yet) and it was unclear that this can be parameterized.

**Pull request merged**
